apiVersion: integration/v1
kind: Step
name: task-run-start-wait
version: 1
summary: Start a Puppet/Bolt task run and wait for the results

description: |
  Requests a new task run using the Relay API. When you have specified the 
  `wait_for_results` as true, Relay will wait until the task is finished and
  store the results.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/puppet-step-task-run-start

examples:
- summary: Request a new task run and wait for the results
  content:
    apiVersion: v1
    kind: Step
    name: start-task-run-wait
    image: relaysh/puppet-step-task-run-start-wait
    spec:
      connection: !Connection {type: puppet, name: my-pe-connection}
      environment: !Parameter puppetEnvironment
      name: 'aws::create_instance'
      wait_for_results: true
      params:
        image_id: ami-0928f4202481dfdf6
        region: us-west-1

schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json
